### PR TITLE
Update dependencies and adapted react-redux-router implementation

### PR DESCRIPTION
**Pull request by scerelli**

### CODE REVIEW

**Comment by tj** [comment]
sweet thanks!

**Comment by josescasanova** [comment]
Awesome

**Comment by tj** [comment]
I should ask, is this the latest version of react-redux-router? I know they were talking about changing the API again, maybe that's still in flux

**Comment by scerelli** [comment]
@tj please excuse me for taking so long to answer.
btw is the last i found the day i opened the PR :)

**Pull request merged**
