### PR TITLE
Update postcss-modules version

### PR DESCRIPTION
**Pull request by madyankin**

### CODE REVIEW

**Comment by mikaa123** [comment]
Do we directly use postcss-modules ? I thought CSS Modules were provided throught the css-loader's modules attribute.

**Comment by madyankin** [comment]
@mikaa123 postcss-modules are created primarly for server-side and webpackless usage.

**Comment by tj** [comment]
I thought I had it in there, now I'm confused by webpack's config again hahaha

**Comment by tj** [comment]
yea I don't see it, might be fine to remove?

**Comment by mikaa123** [comment]
@tj yup, removing it wouldn't impact the stack :) However, it would be good to use if you intend to make the stack isomorphic

**Comment by tj** [comment]
nah I don't, I'll remove it, must have been a left-over dep

**Pull request merged**
